theme: minima
title: My Portfolio
author: Stefan Moore
email: stefan.d.moore@outlook.com
description: > # this means to ignore newlines until "baseurl:"
Becoming a programmer without a degree or experience.

# social links
github_username:  StefanMoore # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
